name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      # 必要なファイルを ZIP にまとめる
      - name: Package plugin
        run: |
          PLUGIN_NAME="obsidian-vault-organizer-plugin"
          mkdir "$PLUGIN_NAME"
          cp main.js "$PLUGIN_NAME/"
          cp manifest.json "$PLUGIN_NAME/"
          cp styles.css "$PLUGIN_NAME/"
          zip -r "$PLUGIN_NAME.zip" "$PLUGIN_NAME/"

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF##*/}"

          gh release create "$TAG" \
            --title="Release $TAG" \
            --notes="New release of $PLUGIN_NAME" \
            --draft \
            obsidian-vault-organizer-plugin.zip